//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.folioFilesSR {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="folioFilesSR.folioFilesSoap")]
    public interface folioFilesSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ConsoleApp2.folioFilesSR.HelloWorldResponse HelloWorld(ConsoleApp2.folioFilesSR.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp2.folioFilesSR.HelloWorldResponse> HelloWorldAsync(ConsoleApp2.folioFilesSR.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name claveFolio from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/folioFiles", ReplyAction="*")]
        ConsoleApp2.folioFilesSR.folioFilesResponse folioFiles(ConsoleApp2.folioFilesSR.folioFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/folioFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp2.folioFilesSR.folioFilesResponse> folioFilesAsync(ConsoleApp2.folioFilesSR.folioFilesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.folioFilesSR.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ConsoleApp2.folioFilesSR.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.folioFilesSR.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ConsoleApp2.folioFilesSR.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class folioFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="folioFiles", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.folioFilesSR.folioFilesRequestBody Body;
        
        public folioFilesRequest() {
        }
        
        public folioFilesRequest(ConsoleApp2.folioFilesSR.folioFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class folioFilesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string claveFolio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string claveNombreFile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string code;
        
        public folioFilesRequestBody() {
        }
        
        public folioFilesRequestBody(string claveFolio, string claveNombreFile, string code) {
            this.claveFolio = claveFolio;
            this.claveNombreFile = claveNombreFile;
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class folioFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="folioFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp2.folioFilesSR.folioFilesResponseBody Body;
        
        public folioFilesResponse() {
        }
        
        public folioFilesResponse(ConsoleApp2.folioFilesSR.folioFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class folioFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string folioFilesResult;
        
        public folioFilesResponseBody() {
        }
        
        public folioFilesResponseBody(string folioFilesResult) {
            this.folioFilesResult = folioFilesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface folioFilesSoapChannel : ConsoleApp2.folioFilesSR.folioFilesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class folioFilesSoapClient : System.ServiceModel.ClientBase<ConsoleApp2.folioFilesSR.folioFilesSoap>, ConsoleApp2.folioFilesSR.folioFilesSoap {
        
        public folioFilesSoapClient() {
        }
        
        public folioFilesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public folioFilesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public folioFilesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public folioFilesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp2.folioFilesSR.HelloWorldResponse ConsoleApp2.folioFilesSR.folioFilesSoap.HelloWorld(ConsoleApp2.folioFilesSR.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ConsoleApp2.folioFilesSR.HelloWorldRequest inValue = new ConsoleApp2.folioFilesSR.HelloWorldRequest();
            inValue.Body = new ConsoleApp2.folioFilesSR.HelloWorldRequestBody();
            ConsoleApp2.folioFilesSR.HelloWorldResponse retVal = ((ConsoleApp2.folioFilesSR.folioFilesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp2.folioFilesSR.HelloWorldResponse> ConsoleApp2.folioFilesSR.folioFilesSoap.HelloWorldAsync(ConsoleApp2.folioFilesSR.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp2.folioFilesSR.HelloWorldResponse> HelloWorldAsync() {
            ConsoleApp2.folioFilesSR.HelloWorldRequest inValue = new ConsoleApp2.folioFilesSR.HelloWorldRequest();
            inValue.Body = new ConsoleApp2.folioFilesSR.HelloWorldRequestBody();
            return ((ConsoleApp2.folioFilesSR.folioFilesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp2.folioFilesSR.folioFilesResponse ConsoleApp2.folioFilesSR.folioFilesSoap.folioFiles(ConsoleApp2.folioFilesSR.folioFilesRequest request) {
            return base.Channel.folioFiles(request);
        }
        
        public string folioFiles(string claveFolio, string claveNombreFile, string code) {
            ConsoleApp2.folioFilesSR.folioFilesRequest inValue = new ConsoleApp2.folioFilesSR.folioFilesRequest();
            inValue.Body = new ConsoleApp2.folioFilesSR.folioFilesRequestBody();
            inValue.Body.claveFolio = claveFolio;
            inValue.Body.claveNombreFile = claveNombreFile;
            inValue.Body.code = code;
            ConsoleApp2.folioFilesSR.folioFilesResponse retVal = ((ConsoleApp2.folioFilesSR.folioFilesSoap)(this)).folioFiles(inValue);
            return retVal.Body.folioFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp2.folioFilesSR.folioFilesResponse> ConsoleApp2.folioFilesSR.folioFilesSoap.folioFilesAsync(ConsoleApp2.folioFilesSR.folioFilesRequest request) {
            return base.Channel.folioFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp2.folioFilesSR.folioFilesResponse> folioFilesAsync(string claveFolio, string claveNombreFile, string code) {
            ConsoleApp2.folioFilesSR.folioFilesRequest inValue = new ConsoleApp2.folioFilesSR.folioFilesRequest();
            inValue.Body = new ConsoleApp2.folioFilesSR.folioFilesRequestBody();
            inValue.Body.claveFolio = claveFolio;
            inValue.Body.claveNombreFile = claveNombreFile;
            inValue.Body.code = code;
            return ((ConsoleApp2.folioFilesSR.folioFilesSoap)(this)).folioFilesAsync(inValue);
        }
    }
}
