//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2.srEnviarDatos {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="srEnviarDatos.wsRecibirDatosSoap")]
    public interface wsRecibirDatosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld(string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<string> HelloWorldAsync(string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecibirDatosConsulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RecibirDatosConsulta(string LcadEvento, string LcadenaDatosPersonales, string LcadenaAD, string LcadenaEO, string LcadenaBM, string LcadenaMO, string LcadenaPI, System.Data.DataTable LcadenaDC, string LcadenaPlanTx, System.Data.DataTable LcadenaMC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecibirDatosConsulta", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RecibirDatosConsultaAsync(string LcadEvento, string LcadenaDatosPersonales, string LcadenaAD, string LcadenaEO, string LcadenaBM, string LcadenaMO, string LcadenaPI, System.Data.DataTable LcadenaDC, string LcadenaPlanTx, System.Data.DataTable LcadenaMC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsRecibirDatosSoapChannel : ConsoleApp2.srEnviarDatos.wsRecibirDatosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsRecibirDatosSoapClient : System.ServiceModel.ClientBase<ConsoleApp2.srEnviarDatos.wsRecibirDatosSoap>, ConsoleApp2.srEnviarDatos.wsRecibirDatosSoap {
        
        public wsRecibirDatosSoapClient() {
        }
        
        public wsRecibirDatosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsRecibirDatosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRecibirDatosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsRecibirDatosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld(string clave) {
            return base.Channel.HelloWorld(clave);
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync(string clave) {
            return base.Channel.HelloWorldAsync(clave);
        }
        
        public string RecibirDatosConsulta(string LcadEvento, string LcadenaDatosPersonales, string LcadenaAD, string LcadenaEO, string LcadenaBM, string LcadenaMO, string LcadenaPI, System.Data.DataTable LcadenaDC, string LcadenaPlanTx, System.Data.DataTable LcadenaMC) {
            return base.Channel.RecibirDatosConsulta(LcadEvento, LcadenaDatosPersonales, LcadenaAD, LcadenaEO, LcadenaBM, LcadenaMO, LcadenaPI, LcadenaDC, LcadenaPlanTx, LcadenaMC);
        }
        
        public System.Threading.Tasks.Task<string> RecibirDatosConsultaAsync(string LcadEvento, string LcadenaDatosPersonales, string LcadenaAD, string LcadenaEO, string LcadenaBM, string LcadenaMO, string LcadenaPI, System.Data.DataTable LcadenaDC, string LcadenaPlanTx, System.Data.DataTable LcadenaMC) {
            return base.Channel.RecibirDatosConsultaAsync(LcadEvento, LcadenaDatosPersonales, LcadenaAD, LcadenaEO, LcadenaBM, LcadenaMO, LcadenaPI, LcadenaDC, LcadenaPlanTx, LcadenaMC);
        }
    }
}
